version: '3.7'

services:

    hhs-infra-mongo:
        container_name: hhs-infra-mongo_container
        image: mongo:5.0.15
        hostname: hhs_mongo_node_1
        restart: always
        volumes:
            - $HOME/docker-volumes/hhs/mongo/mongo_data_db:/data/db
            - $HOME/docker-volumes/hhs/mongo/mongo_data_config:/data/configdb
            - $HOME/docker-volumes/hhs/mongo/mongo_db:/mongodb
        networks:
            - hhs-network
        ports:
            - "31017:27017"

    hhs-infra-postgres:
        container_name: hhs-infra-postgres_container
        image: postgres:latest
        hostname: hhs_postgres_node_1
        restart: always
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - $HOME/docker-volumes/hhs/postgres/postgresql:/var/lib/postgresql
            - $HOME/docker-volumes/hhs/postgres/postgresql_data:/var/lib/postgresql/data
        networks:
            - hhs-network
        ports:
            - "35432:5432"
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            TZ: "GMT+2"
            LANG: "en_US.utf8"
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale-provider=icu --icu-locale=en_US"

    hhs-infra-redis:
        container_name: hhs-infra-redis_container
        image: redis:latest
        hostname: hhs_redis_node_1
        restart: always
        volumes:
            - $HOME/docker-volumes/hhs/redis/redis_data:/data
        networks:
            - hhs-network
        ports:
            - "36379:6379"

    hhs-infra-rabbitmq:
        container_name: hhs-infra-rabbitmq_container
        image: rabbitmq:3-management
        hostname: hhs_rabbit_node_1
        restart: always
        volumes:
            - $HOME/docker-volumes/hhs/rabbitmq/rabbitmq_data:/var/lib/rabbitmq
        networks:
            - hhs-network
        ports:
            - "35672:5672" #amqp port
            - "45672:15672" # management web console

networks:
    hhs-network:
        name: hhs.infrastructure-network
        driver: bridge
        external: true
